<li>
                <div class="img"> <a href="[field:arcurl/]"></a> <img src="[field:picname/]"/> </div>
                <div class="web">
                  <div class="wd_w"> <span>问</span>
                    <h4><a href="[field:arcurl/]">[field:title/]</a></h4>
                    <div class="clear"></div>
                  </div>
                  <div class="wd_d"> <span>答</span>
                    <p><a href="[field:arcurl/]">[field:description function="cn_substr(@me,140)"/]...</a></p>
                    <div class="clear"></div>
                  </div>
                </div>
                <div class="clear"></div>
              </li>