<div class="item">
              <div class="explosive_list">
                <h4>NO.[field:global.autoindex/]</h4>
                <a href="[field:arcurl/]">
                <div class="img"> <img src="[field:picname/]"/> </div>
                <div class="web">
                  <div class="text">
                    <h3>[field:title/]</h3>
                    <p>[field:typename/]</p>
                  </div>
                  <div class="more">
                    <label>详情</label>
                  </div>
                </div>
                </a> </div>
            </div>