<?php
$z[0]=Array("arclist","\r\n            <div class=\"item\">\r\n              <div class=\"explosive_list\">\r\n                <h4>NO.[field:global.autoindex/]</h4>\r\n                <a href=\"[field:arcurl/]\">\r\n                <div class=\"img\"> <img src=\"[field:picname/]\"/> </div>\r\n                <div class=\"web\">\r\n                  <div class=\"text\">\r\n                    <h3>[field:title/]</h3>\r\n                    <p>[field:typename/]</p>\r\n                  </div>\r\n                  <div class=\"more\">\r\n                    <label>详情</label>\r\n                  </div>\r\n                </div>\r\n                </a> </div>\r\n            </div>\r\n            ",512,1195);
$z[0][4]=array();
$z[0][4]['titlelen']="50";
$z[0][4]['flag']="c";
$z[1]=Array("field","",1396,1425);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("channel","\r\n              <li class=\"wow fadeInUp\"><a href=\"[field:typeurl/]\"><i></i>[field:typename/]</a></li>\r\n              ",1726,2006);
$z[2][4]=array();
$z[2][4]['type']="son";
$z[2][4]['currentstyle']="<li class='on wow fadeInUp'><a href='~typelink~'><i></i>~typename~</a></li>";
$z[3]=Array("field","",2105,2133);
$z[3][4]=array();
$z[3][4]['name']="typeurl";
$z[4]=Array("arclist","\r\n              <li class=\"wow fadeInUp\"> <a href=\"[field:arcurl/]\">\r\n                <div class=\"img\"> <img src=\"[field:picname/]\"/> </div>\r\n                <div class=\"web\">\r\n                  <p>[field:title/]\r\n                    <label>详情</label>\r\n                  </p>\r\n                </div>\r\n                </a> </li>\r\n              ",2296,2712);
$z[4][4]=array();
$z[4][4]['row']="6";
$z[4][4]['titlelen']="50";
$z[4][4]['orderby']="pubdate";

?>