<?php
$z[0]=Array("field","",138,167);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",239,270);
$z[1][4]=array();
$z[1][4]['name']="typenameen";
$z[2]=Array("type","\r\n            <h3>[field:typename/]</h3>\r\n            ",412,501);
$z[2][4]=array();
$z[2][4]['typeid']="16";
$z[3]=Array("arclist","\r\n          <div class=\"img\"> <a href=\"[field:arcurl/]\"></a> <img src=\"[field:picname/]\"/> </div>\r\n          <div class=\"web\">\r\n            <h4><a href=\"[field:arcurl/]\">[field:title/]</a><span>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span></h4>\r\n            <p>[field:description function=\"cn_substr(@me,160)\"/]...</p>\r\n          </div>\r\n          ",520,958);
$z[3][4]=array();
$z[3][4]['typeid']="16";
$z[3][4]['row']="1";
$z[3][4]['titlelen']="50";
$z[3][4]['orderby']="pubdate";
$z[4]=Array("type","\r\n            <h3>[field:typename/]</h3>\r\n            ",1058,1147);
$z[4][4]=array();
$z[4][4]['typeid']="17";
$z[5]=Array("arclist","\r\n              <li>\r\n                <div class=\"img\"> <a href=\"[field:arcurl/]\"></a> <img src=\"[field:picname/]\"/> </div>\r\n                <div class=\"web\">\r\n                  <div class=\"wd_w\"> <span>问</span>\r\n                    <h4><a href=\"[field:arcurl/]\">[field:title/]</a></h4>\r\n                    <div class=\"clear\"></div>\r\n                  </div>\r\n                  <div class=\"wd_d\"> <span>答</span>\r\n                    <p><a href=\"[field:arcurl/]\">[field:description function=\"cn_substr(@me,140)\"/]...</a></p>\r\n                    <div class=\"clear\"></div>\r\n                  </div>\r\n                </div>\r\n                <div class=\"clear\"></div>\r\n              </li>\r\n              ",1218,2004);
$z[5][4]=array();
$z[5][4]['typeid']="17";
$z[5][4]['row']="3";
$z[5][4]['titlelen']="50";
$z[5][4]['orderby']="pubdate";
$z[6]=Array("field","",2130,2158);
$z[6][4]=array();
$z[6][4]['name']="typeurl";

?>