<li>
              <div class="img"> <a href="[field:arcurl/]"></a> <img src="[field:picname/]"/> </div>
              <div class="web">
                <div class="wd_w">
                  <h4><a href="[field:arcurl/]">[field:title/]</a></h4>
                </div>
                <div class="wd_d">
                  <p><a href="[field:arcurl/]">[field:description function="cn_substr(@me,300)"/]...</a></p>
                  <div class="news_xq">
                    <p><a href="[field:title/]">详情</a><em>[field:pubdate function="MyDate('Y-m-d',@me)"/]</em></p>
                  </div>
                </div>
              </div>
              <div class="clear"></div>
            </li>