<?php
$z[0]=Array("field","",151,180);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",252,283);
$z[1][4]=array();
$z[1][4]['name']="typenameen";
$z[2]=Array("sql","\r\n          [field:content function='cn_substr(html2text(@me),600)'/]...\r\n          ",1046,1201);
$z[2][4]=array();
$z[2][4]['sql']="Select content from dede_arctype where id=2";
$z[3]=Array("field","",1243,1271);
$z[3][4]=array();
$z[3][4]['name']="typeurl";

?>