<?php
$z[0]=Array("arcurl","",27,42);
$z[0][4]=array();
$z[1]=Array("picname","",59,75);
$z[1][4]=array();
$z[2]=Array("arcurl","",141,156);
$z[2][4]=array();
$z[3]=Array("title","",158,172);
$z[3][4]=array();
$z[4]=Array("pubdate","",182,229);
$z[4][4]=array();
$z[4][4]['function']="MyDate('Y-m-d',@me)";
$z[5]=Array("description","",258,308);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(@me,160)";

?>