<?php
$z[0]=Array("global","",75,101);
$z[0][4]=array();
$z[0][4]['name']="cfg_cmspath";
$z[1]=Array("global","",114,140);
$z[1][4]=array();
$z[1][4]['name']="cfg_cmspath";
$z[2]=Array("field","(@me==\"\")? @me=\" class='on'\":@me=\"\";",225,311);
$z[2][4]=array();
$z[2][4]['name']="typeid";
$z[2][4]['runphp']="yes";
$z[3]=Array("global","",321,347);
$z[3][4]=array();
$z[3][4]['name']="cfg_cmspath";
$z[4]=Array("channel","\r\n        <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n        ",381,589);
$z[4][4]=array();
$z[4][4]['type']="top";
$z[4][4]['currentstyle']="<li class='on'><a href='~typelink~'>~typename~</a></li>";
$z[5]=Array("global","",678,700);
$z[5][4]=array();
$z[5][4]['name']="cfg_tel";

?>